### PR TITLE
Make Installable

### PR DESCRIPTION
**Pull request by codekoala**
I've added a simple setup.py to make this project installable with pip.  Please have a gander and fix the information that is inaccurate!

### CODE REVIEW

**Comment by dijxtra** [comment]
Thanks for my first ever pull request :-)

**Comment by codekoala** [comment]
No problem! Thanks for the project and for accepting my changes!

Do you have any plans to upload to PyPI?

**Comment by dijxtra** [comment]
Hm, interesting idea. I've never uploaded stuff to PyPI, but I'm currently reading through upload tutorial, and it seems doable. Do you happen to know if there are any tools which automate upload from github to pypi? Or should I just RTFM and do it by hand?

**Comment by codekoala** [comment]
I'm not sure of any tools, but uploading is pretty easy.  Now that you have a
setup.py, you should be able to do something like:

```
python setup.py register
python setup.py sdist --upload
```

The `register` command is only necessary for the first time you try to upload;
after that it's just the `sdist --upload`. I haven't done this myself for quite
some time, so those commands might be a little off.

**Comment by codekoala** [comment]
I should mention that you'll need an account on PyPI, but I think you might be able to create one with the `register` command. You need to login to upload, and it will ask you for your credentials when needed.

**Comment by codekoala** [comment]
Heh, looks like it'll just be `sdist upload`... http://docs.python.org/distutils/uploading.html

**Comment by dijxtra** [comment]
Yeah, I already registered. I'll first test out "setup.py install" on a clean python install when I come home from vacation and then I'll upload it to pypi. Thanks for help!

**Comment by codekoala** [comment]
Thank YOU :)

**Comment by minchinweb** [comment]
@dijxtra Did this ever get added to PyPI?

**Pull request merged**
