### PR TITLE
Some records do not contain a SEX entry

### PR DESCRIPTION
**Pull request by gburca**

### CODE REVIEW

**Comment by dijxtra** [comment]
Thanks for these changes! Sorry for nitpicking, let me know if you need help with my requests.

**Comment by dijxtra** [comment]
There, merged. Thanks for your cooperation. I will now do some editing, so you can pull back from me later today if you wish.

**Comment by dijxtra** [comment]
Huh. You are aware that your code does not pass unit tests? :-D I'll try fixing that.

**Comment by dijxtra** [comment]
I removed -sig from that line.decode, and all tests still pass. Could you, please, write a test which fails if -sig is removed?

**Comment by gburca** [comment]
Well, you comments said: "Yeah, just drop a sample file to the test directory, then I'll merge the pull request and that's that." so that's what I did. I thought you were going to add a test based on the sample file. I'll send you a pull request for a test script.

**Comment by gburca** [comment]
I was aware that the unit test was failing on the new, more comprehensive sample file, and I mentioned that in the comments. I left it up to you to decide how to address the failure since it was occurring in the pre-existing code. Looks like you've fixed it in the recent commits.

**Pull request merged**
